name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew 
    - name: Validate Gradle wrapper
#       uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      run: ./gradlew wrapper
    - name: Build with Gradle
      run: ./gradlew build
    - name: Test All Scenarios
      run: ./gradlew TestScenarios
