name: Build

on:
  push:
    branches: [ go_v2 ]
  pull_request:
    branches: [ go_v2 ]

jobs:
  go-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
          cache: false
      - name: Verify go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: -j 16 --verbose --timeout 20m --max-same-issues=30 --allow-parallel-runners
          skip-cache: true
      - name: Run all tests
        run: go test ./...
      - name: Pretty print tests running time
        # grep: filter out lines like "--- PASS: TestVCS (15.04s)"
        # sed: remove unnecessary characters
        # awk: re-format lines to "PASS: TestVCS (15.04s)"
        # sort: cut into columns by delimiter ' ' (single space) and sort by column 3 (test time in seconds) as numeric type in reverse order (largest comes first)
        # awk: accumulate sum by test time in seconds
        run: grep --color=never -e '--- PASS:' -e '--- FAIL:' test.log | sed 's/[:()]//g' | awk '{print $2,$3,$4}' | sort -t' ' -nk3 -r | awk '{sum += $3; print $1,$2,$3,sum"s"}'
